language: cpp

addons:
  apt:
    packages:
    - clang-3.6
    - qt5-qmake
    - qt5-default
    - qtbase5-dev

env:
    - COMPILER=clang++-3.6

script: qmake -makefile -o Makefile QMAKE_CXX=$COMPILER DevGarden.pro && make

after_success: ./install-tools.rb
