language: cpp
compiler: clang
env:
- DISTRO=ubuntu-trusty

addons:
  apt:
    packages:
    - qt5-qmake
    - qt5-default
    - qtbase5-dev

script: qmake -makefile -o Makefile DevGarden.pro && make

after_success: ./install-tools.rb
